### ISSUE TITLE
Problem hitting endpoints

### ISSUE THREAD

**Issue by biotom** [ClimateMind/climatemind-backend#23]
When I try and hit any of the endpoints (including the one in `test_posting.py`, `http://127.0.0.1:5000/get_user_scores`), I get the attached error in the browser, and the message `FileNotFoundError: [Errno 2] No such file or directory: './climate_mind_ontology'`.  This is the latest code from master, but running the code after cloning from scratch from 'climatemind-backend' fails because of the requirements.txt issue I described previously.
![image](https://user-images.githubusercontent.com/17361382/90340756-5dfa8400-dff2-11ea-9199-cd452e0a1f2e.png)

**Comment by rodriguesk** [comment]
@biotom  now that docker is implemented in the main branch, does this error still occur?
