### ISSUE TITLE
Pillow dependabot security update 

### ISSUE THREAD

**Issue by biotom** [ClimateMind/climatemind-backend#24]
Dependabot opened a security issue for this repo, which it can't automatically fix. There are 4 moderate-severity CVEs, all concerning the Pillow library. Since Pillow is an image library, I'm not sure if we really need it- I'm going to look at why this is being imported and how we can remove it/change the version.

**Comment by biotom** [comment]
I've opened a PR that should address this.

**Comment by rodriguesk** [comment]
Is pillow for the frontend CI/CD?

**Comment by biotom** [comment]
Nope, it's an imaging library- my guess is it's being used by the graph viz stuff.

**Comment by rodriguesk** [comment]
@biotom  did you resolve this?
