### ISSUE TITLE
Replace cypress questions.cy.js with PyTest integration tests.

### ISSUE THREAD

**Issue by danmash** [ClimateMind/climatemind-backend#401]

**Comment by tadakongithub** [comment]
I'd like take on this task. Is there any deadline?

**Comment by danmash** [comment]
Hi @tadakongithub! Thank you for your interest, I really appreciate this 👍
There's no deadline. I'll send a follow-up in the comments in some time if no progress.
Feel free to ask any questions here or via chat https://t.me/climatemind_chat

**Comment by tadakongithub** [comment]
Ok.

**Comment by tadakongithub** [comment]
Hi. I'm a bit new to making tests and python app in general. While I'm writing in vs code, it says import "pytest" could not be resolved. Same goes for flask. Can you advise what to do?

**Comment by danmash** [comment]
@tadakongithub to make able to run the project and pytest you need to setup your docker environment first. Please make sure you follow [the guide ](https://contribute.climatemind.org/v/rest-api/contribute/installation)
Let me know if you have any problems with the installation.

Then you should be able to [run any command](https://contribute.climatemind.org/v/rest-api/contribute/development/work-with-docker#execute-command-in-docker-container) in your docker container and connect to running containers [from your IDE](https://code.visualstudio.com/docs/devcontainers/containers#_attach-to-existing-container)

**Comment by tadakongithub** [comment]
Just made a PR. Let me know if I need to make any changes

**Comment by tadakongithub** [comment]
I used to be able to create a pull request from a working branch of my forked repo to the develop branch of the upstream repo. Now I can't seem to do that. Did something change? Should I push directly to the develop branch of the upstream repo?

**Comment by brianpeiris** [comment]
@tadakongithub You should be able to create multiple pull requests from your fork, but they have to be on unique branches with different names. Is that what you're running into?
I don't have full access to the repo settings here, but I assume nothing changed there. I'm still able to create PRs from my fork.

**Comment by brianpeiris** [comment]
We can close this now that #477 is merged. Thanks!

**Comment by tadakongithub** [comment]
Now that it's merged, the pull request screen looks how it originally looked and it seems I can make a new PR now. I wonder if I cannot make multiple PR from my fork. Or maybe it was simply because my added commits went to the same PR I made.

Thanks for reviewing!

**Comment by brianpeiris** [comment]
You should definitely be able to open multiple PRs from your fork. I've done that a few times for this project. They just have to be from separate branches. 
Let us know if you run into that issue again.
