### ISSUE TITLE
Refactor URL hardcoding

### ISSUE THREAD

**Issue by danmash** [ClimateMind/climatemind-backend#422]
### What to refactor?

There are cases in the codebase when we are using hardcoding URLs to the project web app: 

- app.models.PasswordResetLink.reset_url
- app/sendgrid/templates/reset_password.py template and usage
- app/sendgrid/templates/user_b_shared_email.py template and usage
- app/sendgrid/templates/welcome_email.py template and usage

### Refactor reason

The refactoring is needed because we need the ability to use different URLs per environment:

- production with analytics https://app.climatemind.org/
- _TBD production without analytics https://app-frontend-prod-001.azurewebsites.net/_ (could be omitted)
- staging https://app-frontend-test-001.azurewebsites.net/
- local docker 
- pytest 

### Suggested solution

- [ ] Update all configs from `config.py` to use the env variable with URL (this solution doesn't suitable for many production envs I suppose, but it's ok for now)

### Acceptance criteria 
- [ ] missing ENV variable shouldn't lead to an error, default config value should be prod

### Tests

- [ ] manual tests
- [ ] unit tests with mocking for the class method
- [ ] integration tests with mocking for emails

**Comment by brianpeiris** [comment]
I can look into this

**Comment by danmash** [comment]
I've added env variable to staging and it works fine
<img width="611" alt="Screenshot 2022-11-28 at 14 38 59" src="https://user-images.githubusercontent.com/3535056/204305274-ed33952f-9cf9-410f-ad06-248e93838168.png">
