### ISSUE TITLE
As a user, I want to delete my account

### ISSUE THREAD

**Issue by danmash** [ClimateMind/climatemind-backend#426]
# User story

As a user, I want to delete my account, so I can remove all my data from the app

# Acceptance criteria

- [ ] Only the user himself could remove his account.
- [ ] All data related to the user removed as well
- [ ] unit test
- [ ] documentation for the endpoint

**Comment by Nehemiah60** [comment]
Hello, I would like to be assigned this task. However, there is one aspect I have not grasped yet from the codebase-my local environment only displays the front-end. I would wish to understand how I can make a connection to the DB in my local machine, and test if my endpoints are working before making any commits. Kindly, I will appreciate your help.

**Comment by danmash** [comment]
Hi Nehemiah. Sure, you can take this one. 
Thank you for letting me know about the issue you face during project installation on your windows machine. I'll double-check if there are any issues. If you have something to add, for example, a full docker container log, please do this in the corresponding issue https://github.com/ClimateMind/climatemind-backend/issues/447

Meanwhile, I hope you are able to plan architecture and your code changes for the user deletion function. 
Feel free to ask me any questions. We've just created a chat for the project https://t.me/climatemind_chat you can find me there

**Comment by danmash** [comment]
Hi @Nehemiah60, 
do you have any further questions?

**Comment by Nehemiah60** [comment]
> Hi @Nehemiah60, do you have any further questions?

Yes, I am getting this error when trying to commit my changes....
remote: Permission to ClimateMind/climatemind-backend.git denied to Nehemiah60.

**Comment by danmash** [comment]
@Nehemiah60 yeah, probably you need to do the following
- [create a fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) 
- then change the [git origin to your fork](https://stackoverflow.com/a/5749266)
- push a new branch to your fork 
- make [a PR to the original ](https://stackoverflow.com/a/39590561)repository from your fork

Hope this will help. If not, let me know. You can write to me in the[ telegram chat](https://t.me/climatemind_chat). 

sorry about the misleading documentation, I'll change this next week.

**Comment by Nehemiah60** [comment]
> @Nehemiah60 yeah, probably you need to do the following
> 
> * [create a fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo)
> * then change the [git origin to your fork](https://stackoverflow.com/a/5749266)
> * push a new branch to your fork
> * make [a PR to the original ](https://stackoverflow.com/a/39590561)repository from your fork
> 
> Hope this will help. If not, let me know. You can write to me in the[ telegram chat](https://t.me/climatemind_chat).
> 
> sorry about the misleading documentation, I'll change this next week.

Hello Dan. I just wanted to have a little conversation. Let me know when available so that I can send a video link. Thanks.

**Comment by Nehemiah60** [comment]
> @Nehemiah60 yeah, probably you need to do the following
> 
> * [create a fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo)
> * then change the [git origin to your fork](https://stackoverflow.com/a/5749266)
> * push a new branch to your fork
> * make [a PR to the original ](https://stackoverflow.com/a/39590561)repository from your fork
> 
> Hope this will help. If not, let me know. You can write to me in the[ telegram chat](https://t.me/climatemind_chat).
> 
> sorry about the misleading documentation, I'll change this next week.

Also Dan my Telegram is also restricted. I am being told I send spam messages. So maybe I might not be able to send messages, as it shows te red notifications on my messages. I am waiting for you to join the meeting since I sent the link on Telegram. Thanks.

**Comment by danmash** [comment]
@Nehemiah60 I recommend you to start from this first https://github.com/ClimateMind/climatemind-backend/issues/396
to figure out how to use pytest
