### ISSUE TITLE
Fix services.webapp.environment.CHOKIDAR_USEPOLLING contains true, which is an invalid type, it should be a string, number, or a null

### ISSUE THREAD

**Issue by rscarrasco** [ClimateMind/climatemind-backend#437]
### Describe the bug

I just forked the repo, and cloned it in my computer. I then proceeded to [run it locally](https://github.com/rscarrasco/climatemind-backend/blob/develop/docs/contribute-as-a-python-dev/installation.md#up-containers), but when I issued:

```
docker-compose -p climatemind-backend --profile webapp -f docker/docker-compose.yml up -d --build
```

it threw the following:

```
ERROR: The Compose file './docker/docker-compose.yml' is invalid because:
services.webapp.environment.CHOKIDAR_USEPOLLING contains true, which is an invalid type, it should be a string, number, or a null
```

My environment:

  * Docker  20.10.12.
  * Docker Compose 1.29.2
  * Linux Mint 21

### To Reproduce

Steps to reproduce the issue:

- `cd` into the project directory.
- run the following:

```
docker-compose -p climatemind-backend --profile webapp -f docker/docker-compose.yml up -d --build
```

### Expected behavior

I expected no error message from the above command.

### Task

- [ ] Check out if quoting the `true` literal at  `CHOKIDAR_USEPOLLING: true` (file `docker/docker-compose.yml`) fixes the problem.

**Comment by danmash** [comment]
@rscarrasco nicely done!
I am unable to check this at the moment since I use M1 mac and can't build `docker/docker-compose.yml`
Could you please check this quoting and let me know? You could also create a PR which will be merged ASAP.
Anyway, thank you! I really appreciate this 👍

**Comment by rscarrasco** [comment]
@danmash thanks!

I was trying just that...I tried quoting, and it seems to be working just fine. I then tried something else: removing it altogether. I issued:

```
grep -ri chokidar .
```

and 

```
find . -name "*chokidar*"
```
but nothing was found. This leads me to wonder if Chokidar is even used at all. I tried removing it from the `docker/docker-compose.yml, deleting all related images/containers, and rebuilding. The system ran as before.

I'm not sure if I can remove it, but I'll send a PR removing Chokidar anyway.

**Comment by danmash** [comment]
You are probably right. If I understand correctly it is needed only for [development](https://stackoverflow.com/a/44643246/2207154) and we can omit it since we don't change any files and use the ready-to-go docker image. Please correct me if I'm wrong. 
@Svenstar74 please correct me if I'm wrong.
