### ISSUE TITLE
Check Windows installation

### ISSUE THREAD

**Issue by danmash** [ClimateMind/climatemind-backend#447]
### Discussed in https://github.com/ClimateMind/climatemind-backend/discussions/446

<div type='discussions-op-text'>

<sup>Originally posted by **Nehemiah60** November  7, 2022</sup>
I am not sure but I think there should be updates on the installation guide. On my windows machine, all the containers were running but the api-1 would exit almost instantly. The log files showed the error: /usr/bin/env bash\r: No such file or directory. I had to research and the solution was to use a windows Ubuntu Subsystem to clone the repo.</div>

**Comment by danmash** [comment]
@Nehemiah60 looks like you were right, we just need some documentation update. There's a note for Windows users about autocrlf 
The thing is you need to set this git config --global first, and only then git clone repository. 

I recommend you do the following: 
- rm -Recurse -Force .\climatemind-backend\
- git config --global core.autocrlf false
- git clone https://github.com/ClimateMind/climatemind-backend.git 
- cd climatemind-backend
- docker-compose -p climatemind-backend --profile webapp -f docker/docker-compose.yml up -d --build
- 
![image](https://user-images.githubusercontent.com/3535056/200449274-bc7cdbe5-d577-4dbc-a57b-351436b8a2d6.png)

**Comment by danmash** [comment]
@Nehemiah60 the docs updated 
Thank you for reporting this! I really appreciate this 👍

**Comment by Nehemiah60** [comment]
That is great. I will embark on working on the assigned issue.
