### ISSUE TITLE
documentation problem?

### ISSUE THREAD

**Issue by andrew-banister** [ClimateMind/climatemind-backend#47]
When I run the backend app locally, I get the message " Running on http://0.0.0.0:5000" but then when I go to that page on my browser I get the message "This site can't be reached".
However, if I go to "http://127.0.0.1:5000" then it works. Can the app be fixed so the url mentioned in the terminal is actually the right url I need to go to? And if that can't be fixed, then can this issue at least be mentioned in the readme so other people don't struggle trying to figure out the right url to go to?

![Annotation 2020-09-09 213711 API broken](https://user-images.githubusercontent.com/4675257/92682576-8752bb00-f2e5-11ea-83cd-9c6e2470d463.png)
![Annotation 2020-09-09 213711 API](https://user-images.githubusercontent.com/4675257/92682578-87eb5180-f2e5-11ea-9b20-fddfe74a3189.png)
![Annotation 2020-09-09 213711](https://user-images.githubusercontent.com/4675257/92682579-87eb5180-f2e5-11ea-996e-da3d6a8b64bc.png)

**Comment by seanmajorpayne** [comment]
That sounds like a docker issue rather than an application issue.

If I run the application locally it says it's running on the 127 address.

We can update the documentation to suggest this address though.

**Comment by rodriguesk** [comment]
Added a note for this in the README.
