### ISSUE TITLE
Missing troubleshooting instructions for failed database migration during installation

### ISSUE THREAD

**Issue by cjamesanderson** [ClimateMind/climatemind-backend#479]
### Add troubleshooting instructions for failed database migration during installation

Sometimes the database can fail to migrate during initial installation resulting in odd behavior like a local webapp frontpage which loads but is only partially functional and generates an error message: "Something went wrong initializing your session. :( Please refresh the page to try again."

- [ ] Add a troubleshooting guide to [docs/contribute/installation.md](https://github.com/ClimateMind/climatemind-backend/blob/a66e865c2953ce8b68942781a2a45b1e8733d88c/docs/contribute/installation.md) for resolving this issue.

**Comment by danmash** [comment]
👍
